# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/seibpy',
                'doc_host': 'https://franckalbinet.github.io',
                'git_url': 'https://github.com/franckalbinet/seibpy',
                'lib_path': 'seibpy'},
  'syms': {'seibpy.core': {'seibpy.core.foo': ('core.html#foo', 'seibpy/core.py')}}}
